//! Test HIP implementation against official rwkvfla ground truth.
//!
//! These tests validate that the HIP RWKV7 implementation produces outputs
//! matching the official rwkvfla.ops.rwkv7.chunk_rwkv7 Triton kernel.
//!
//! Fixtures generated by: scripts/extract_rwkv7_fixtures.py
//! Test prompt: "<|endoftext|>User: what is the capital of France?\nAssistant:"

mod common;

use common::{assert_tensors_close, TestFixture};
use std::path::Path;

fn model_exists() -> bool {
    Path::new("/workspace/models/rwkv7-g1a-0.1b-20250728-ctx4096.st").exists()
}

fn ground_truth_fixtures_exist() -> bool {
    Path::new("tests/fixtures/ground_truth/config.npz").exists()
        && Path::new("tests/fixtures/ground_truth/step_0.npz").exists()
}

/// Test HIP model forward pass against official rwkvfla ground truth.
///
/// This is the primary validation that our HIP implementation matches
/// the reference implementation. Processes 14 tokens sequentially and
/// compares logits at each step.
#[test]
#[cfg(feature = "hip")]
fn test_hip_against_ground_truth() {
    if !model_exists() {
        eprintln!("Skipping test: model file not found at /workspace/models/rwkv7-g1a-0.1b-20250728-ctx4096.st");
        return;
    }
    if !ground_truth_fixtures_exist() {
        eprintln!("Skipping test: ground truth fixtures not found at tests/fixtures/ground_truth/");
        eprintln!("Generate with: python scripts/extract_rwkv7_fixtures.py --model /path/to/model.pth");
        return;
    }

    // Load config to get token sequence
    let config = TestFixture::load("tests/fixtures/ground_truth/config.npz")
        .expect("Failed to load config");
    let tokens_i64 = config.i64("tokens");
    let n_steps = config.i64("n_steps")[0] as usize;

    println!("Testing HIP against ground truth:");
    println!("  Tokens: {:?}", tokens_i64);
    println!("  Steps: {}", n_steps);

    // Load model
    let model = web_rwkv::hip::Rwkv7Hip::load("/workspace/models/rwkv7-g1a-0.1b-20250728-ctx4096.st")
        .expect("Failed to load model");

    // Create state for streaming inference
    let mut state = web_rwkv::hip::HipState::new(&model.info, 1);

    // Process each token and compare logits
    let mut all_passed = true;
    for step in 0..n_steps {
        let token = tokens_i64[step] as u32;
        let fixture_path = format!("tests/fixtures/ground_truth/step_{}.npz", step);
        let fixture = TestFixture::load(&fixture_path)
            .expect(&format!("Failed to load {}", fixture_path));

        // Run single token through HIP model
        let logits = model.forward_with_state(&[&[token]], &mut state)
            .expect(&format!("Forward pass failed at step {}", step));

        // Load expected logits from fixture
        let expected_logits = fixture.f32("logits");

        // Compare logits (rtol=1e-2, atol=1e-3 per plan)
        let result = assert_tensors_close(&logits, expected_logits, 1e-2, 1e-3);

        match result {
            Ok(()) => {
                // Find top prediction
                let (max_idx, max_val) = logits.iter().enumerate()
                    .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
                    .unwrap();
                println!("  Step {}: token {} -> top prediction {} (logit {:.4}) OK",
                         step, token, max_idx, max_val);
            }
            Err(e) => {
                eprintln!("  Step {}: token {} FAILED: {}", step, token, e);

                // Debug: show top-5 predictions from both
                let mut indexed: Vec<_> = logits.iter().enumerate().collect();
                indexed.sort_by(|(_, a), (_, b)| b.partial_cmp(a).unwrap());
                eprintln!("    HIP top-5: {:?}", &indexed[..5]);

                let mut expected_indexed: Vec<_> = expected_logits.iter().enumerate().collect();
                expected_indexed.sort_by(|(_, a), (_, b)| b.partial_cmp(a).unwrap());
                eprintln!("    Expected top-5: {:?}", &expected_indexed[..5]);

                all_passed = false;
            }
        }
    }

    assert!(all_passed, "Some steps failed ground truth comparison");
    println!("\nAll {} steps passed ground truth validation!", n_steps);
}

/// Test that final logits produce expected next token prediction.
///
/// After processing the full prompt, the model should predict a reasonable
/// continuation. This is a sanity check that the model is working.
#[test]
#[cfg(feature = "hip")]
fn test_ground_truth_final_prediction() {
    if !model_exists() || !ground_truth_fixtures_exist() {
        eprintln!("Skipping test: model or fixtures not found");
        return;
    }

    // Load final step fixture
    let config = TestFixture::load("tests/fixtures/ground_truth/config.npz")
        .expect("Failed to load config");
    let n_steps = config.i64("n_steps")[0] as usize;

    let final_fixture = TestFixture::load(&format!("tests/fixtures/ground_truth/step_{}.npz", n_steps - 1))
        .expect("Failed to load final step fixture");
    let expected_logits = final_fixture.f32("logits");

    // Find argmax of expected logits
    let (expected_argmax, _) = expected_logits.iter().enumerate()
        .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
        .unwrap();

    println!("Final step (after 'Assistant:') expects token {}", expected_argmax);

    // The expected next token after "Assistant:" should be reasonable
    // (e.g., a space, newline, or start of response)
    // Token 262 = " The", Token 11 = "\n", Token 209 = " "
    let reasonable_tokens = [262, 11, 209, 380, 586, 1703]; // Common response starts

    println!("Expected argmax: {}", expected_argmax);
    println!("Reasonable tokens: {:?}", reasonable_tokens);
}
