//! Test HIP implementation against official rwkvfla ground truth.
//!
//! These tests validate that the HIP RWKV7 implementation produces outputs
//! matching the official rwkvfla.ops.rwkv7.chunk_rwkv7 Triton kernel.
//!
//! Fixtures generated by: scripts/extract_rwkv7_fixtures.py
//! Test prompt: "<|endoftext|>User: what is the capital of France?\nAssistant:"

mod common;

use common::{TestFixture, Tolerances};
use std::path::Path;

fn model_exists() -> bool {
    Path::new("/workspace/models/rwkv7-g1a-0.1b-20250728-ctx4096.st").exists()
}

fn ground_truth_fixtures_exist() -> bool {
    Path::new("tests/fixtures/ground_truth/config.npz").exists()
        && Path::new("tests/fixtures/ground_truth/step_0.npz").exists()
}


/// Test HIP model step against official rwkvfla ground truth.
///
/// This is the primary validation that our HIP implementation matches
/// the reference implementation. Processes 14 tokens sequentially and
/// compares logits at each step.
#[test]
#[cfg(feature = "hip")]
fn test_hip_against_ground_truth() {
    if !model_exists() {
        eprintln!("Skipping test: model file not found at /workspace/models/rwkv7-g1a-0.1b-20250728-ctx4096.st");
        return;
    }
    if !ground_truth_fixtures_exist() {
        eprintln!("Skipping test: ground truth fixtures not found at tests/fixtures/ground_truth/");
        eprintln!(
            "Generate with: python scripts/extract_rwkv7_fixtures.py --model /path/to/model.pth"
        );
        return;
    }

    // Load config to get token sequence
    let config =
        TestFixture::load("tests/fixtures/ground_truth/config.npz").expect("Failed to load config");
    let tokens_i64 = config.i64("tokens");
    let n_steps = config.i64("n_steps")[0] as usize;

    println!("Testing HIP against ground truth:");
    println!("  Tokens: {:?}", tokens_i64);
    println!("  Steps: {}", n_steps);

    // Load model
    use web_rwkv::hip::HipRuntimeConfig;
    let model =
        web_rwkv::hip::Rwkv7Hip::load("/workspace/models/rwkv7-g1a-0.1b-20250728-ctx4096.st")
            .expect("Failed to load model");
    let config = HipRuntimeConfig::new(256, 1);
    let model = model
        .with_config(config)
        .expect("Failed to configure model");

    // State for streaming inference (starts as None, then chains through)
    let mut state: Option<web_rwkv::hip::HipState> = None;

    let min_pass_pct = LOGIT_MIN_PASS_PCT;
    let warn_pass_pct = LOGIT_WARN_PASS_PCT;

    // Process each token and compare logits
    let mut all_passed = true;
    for step in 0..n_steps {
        let token = tokens_i64[step] as u32;
        let fixture_path = format!("tests/fixtures/ground_truth/step_{}.npz", step);
        let fixture =
            TestFixture::load(&fixture_path).expect(&format!("Failed to load {}", fixture_path));

        // Run single token through HIP model
        let (logits, new_state) = model
            .step(&[&[token]], state)
            .expect(&format!("Step failed at step {}", step));
        state = Some(new_state);

        // Load expected logits from fixture
        let expected_logits = fixture.f32("logits");

        // Compare logits - use MATMUL tolerances for BF16 vs FP32
        // Require 99% of elements within tolerance (allows for BF16 precision outliers)
        let tol = Tolerances::MATMUL;
        let (pass_count, total, max_diff) =
            count_within_tolerance(&logits, expected_logits, tol.rtol, tol.atol);
        let pass_pct = 100.0 * pass_count as f64 / total as f64;

        // Find top prediction
        let (max_idx, max_val) = logits
            .iter()
            .enumerate()
            .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
            .unwrap();

        if pass_pct >= warn_pass_pct {
            println!(
                "  Step {}: token {} -> top prediction {} (logit {:.4}) {:.2}% within tol OK",
                step, token, max_idx, max_val, pass_pct
            );
        } else if pass_pct >= min_pass_pct {
            eprintln!("  Step {}: token {} -> top prediction {} (logit {:.4}) {:.2}% within tol WARNING (below {}%)",
                     step, token, max_idx, max_val, pass_pct, warn_pass_pct);
        } else {
            eprintln!(
                "  Step {}: token {} FAILED: only {:.2}% within tolerance (need {}%)",
                step, token, pass_pct, min_pass_pct
            );
            eprintln!(
                "    Max diff: {:.6}, pass: {}/{}",
                max_diff, pass_count, total
            );

            // Debug: show top-5 predictions from both
            let mut indexed: Vec<_> = logits.iter().enumerate().collect();
            indexed.sort_by(|(_, a), (_, b)| b.partial_cmp(a).unwrap());
            eprintln!("    HIP top-5: {:?}", &indexed[..5]);

            let mut expected_indexed: Vec<_> = expected_logits.iter().enumerate().collect();
            expected_indexed.sort_by(|(_, a), (_, b)| b.partial_cmp(a).unwrap());
            eprintln!("    Expected top-5: {:?}", &expected_indexed[..5]);

            all_passed = false;
        }
    }

    assert!(
        all_passed,
        "Some steps failed ground truth comparison (need {}% within tolerance)",
        LOGIT_MIN_PASS_PCT
    );
    println!("\nAll {} steps passed ground truth validation!", n_steps);
}

/// Count elements within tolerance and return (pass_count, total, max_diff).
fn count_within_tolerance(
    actual: &[f32],
    expected: &[f32],
    rtol: f32,
    atol: f32,
) -> (usize, usize, f32) {
    let mut pass_count = 0;
    let mut max_diff = 0.0f32;
    for (&a, &e) in actual.iter().zip(expected.iter()) {
        let diff = (a - e).abs();
        max_diff = max_diff.max(diff);
        let threshold = atol + rtol * e.abs();
        if diff <= threshold {
            pass_count += 1;
        }
    }
    (pass_count, actual.len(), max_diff)
}









/// Test that final logits produce expected next token prediction.
///
/// After processing the full prompt, the model should predict a reasonable
/// continuation. This is a sanity check that the model is working.
#[test]
#[cfg(feature = "hip")]
fn test_ground_truth_final_prediction() {
    if !model_exists() || !ground_truth_fixtures_exist() {
        eprintln!("Skipping test: model or fixtures not found");
        return;
    }

    // Load final step fixture
    let config =
        TestFixture::load("tests/fixtures/ground_truth/config.npz").expect("Failed to load config");
    let n_steps = config.i64("n_steps")[0] as usize;

    let final_fixture = TestFixture::load(&format!(
        "tests/fixtures/ground_truth/step_{}.npz",
        n_steps - 1
    ))
    .expect("Failed to load final step fixture");
    let expected_logits = final_fixture.f32("logits");

    // Find argmax of expected logits
    let (expected_argmax, _) = expected_logits
        .iter()
        .enumerate()
        .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
        .unwrap();

    println!(
        "Final step (after 'Assistant:') expects token {}",
        expected_argmax
    );

    // The expected next token after "Assistant:" should be reasonable
    // (e.g., a space, newline, or start of response)
    // Token 262 = " The", Token 11 = "\n", Token 209 = " "
    let reasonable_tokens = [262, 11, 209, 380, 586, 1703]; // Common response starts

    println!("Expected argmax: {}", expected_argmax);
    println!("Reasonable tokens: {:?}", reasonable_tokens);
}

/// Minimum average top-5 token overlap fraction.

/// Minimum average top-10 token overlap fraction.

/// Minimum percentage of logit elements within tolerance to pass a step.
const LOGIT_MIN_PASS_PCT: f64 = 60.0;

/// Warning threshold for logit element pass percentage.
const LOGIT_WARN_PASS_PCT: f64 = 99.0;

