//! Test HIP implementation against official rwkvfla ground truth.
//!
//! These tests validate that the HIP RWKV7 implementation produces outputs
//! matching the official rwkvfla.ops.rwkv7.chunk_rwkv7 Triton kernel.
//!
//! Fixtures generated by: scripts/extract_rwkv7_fixtures.py
//! Test prompt: "<|endoftext|>User: what is the capital of France?\nAssistant:"

mod common;

use common::{assert_tensors_close, TestFixture, Tolerances};
use std::path::Path;

fn model_exists() -> bool {
    Path::new("/workspace/models/rwkv7-g1a-0.1b-20250728-ctx4096.st").exists()
}

fn ground_truth_fixtures_exist() -> bool {
    Path::new("tests/fixtures/ground_truth/config.npz").exists()
        && Path::new("tests/fixtures/ground_truth/step_0.npz").exists()
}

/// Test HIP model step against official rwkvfla ground truth.
///
/// This is the primary validation that our HIP implementation matches
/// the reference implementation. Processes 14 tokens sequentially and
/// compares logits at each step.
#[test]
#[cfg(feature = "hip")]
fn test_hip_against_ground_truth() {
    if !model_exists() {
        eprintln!("Skipping test: model file not found at /workspace/models/rwkv7-g1a-0.1b-20250728-ctx4096.st");
        return;
    }
    if !ground_truth_fixtures_exist() {
        eprintln!("Skipping test: ground truth fixtures not found at tests/fixtures/ground_truth/");
        eprintln!(
            "Generate with: python scripts/extract_rwkv7_fixtures.py --model /path/to/model.pth"
        );
        return;
    }

    // Load config to get token sequence
    let config =
        TestFixture::load("tests/fixtures/ground_truth/config.npz").expect("Failed to load config");
    let tokens_i64 = config.i64("tokens");
    let n_steps = config.i64("n_steps")[0] as usize;

    println!("Testing HIP against ground truth:");
    println!("  Tokens: {:?}", tokens_i64);
    println!("  Steps: {}", n_steps);

    // Load model
    use web_rwkv::hip::HipRuntimeConfig;
    let model =
        web_rwkv::hip::Rwkv7Hip::load("/workspace/models/rwkv7-g1a-0.1b-20250728-ctx4096.st")
            .expect("Failed to load model");
    let config = HipRuntimeConfig::new(256, 1);
    let model = model
        .with_config(config)
        .expect("Failed to configure model");

    // State for streaming inference (starts as None, then chains through)
    let mut state: Option<web_rwkv::hip::HipState> = None;

    // 75% hard threshold, warn if below 99%
    const MIN_PASS_PCT: f64 = 60.0;
    const WARN_PASS_PCT: f64 = 99.0;

    // Process each token and compare logits
    let mut all_passed = true;
    for step in 0..n_steps {
        let token = tokens_i64[step] as u32;
        let fixture_path = format!("tests/fixtures/ground_truth/step_{}.npz", step);
        let fixture =
            TestFixture::load(&fixture_path).expect(&format!("Failed to load {}", fixture_path));

        // Run single token through HIP model
        let (logits, new_state) = model
            .step(&[&[token]], state)
            .expect(&format!("Step failed at step {}", step));
        state = Some(new_state);

        // Load expected logits from fixture
        let expected_logits = fixture.f32("logits");

        // Compare logits - use MATMUL tolerances for BF16 vs FP32
        // Require 99% of elements within tolerance (allows for BF16 precision outliers)
        let tol = Tolerances::MATMUL;
        let (pass_count, total, max_diff) =
            count_within_tolerance(&logits, expected_logits, tol.rtol, tol.atol);
        let pass_pct = 100.0 * pass_count as f64 / total as f64;

        // Find top prediction
        let (max_idx, max_val) = logits
            .iter()
            .enumerate()
            .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
            .unwrap();

        if pass_pct >= WARN_PASS_PCT {
            println!(
                "  Step {}: token {} -> top prediction {} (logit {:.4}) {:.2}% within tol OK",
                step, token, max_idx, max_val, pass_pct
            );
        } else if pass_pct >= MIN_PASS_PCT {
            eprintln!("  Step {}: token {} -> top prediction {} (logit {:.4}) {:.2}% within tol WARNING (below {}%)",
                     step, token, max_idx, max_val, pass_pct, WARN_PASS_PCT);
        } else {
            eprintln!(
                "  Step {}: token {} FAILED: only {:.2}% within tolerance (need {}%)",
                step, token, pass_pct, MIN_PASS_PCT
            );
            eprintln!(
                "    Max diff: {:.6}, pass: {}/{}",
                max_diff, pass_count, total
            );

            // Debug: show top-5 predictions from both
            let mut indexed: Vec<_> = logits.iter().enumerate().collect();
            indexed.sort_by(|(_, a), (_, b)| b.partial_cmp(a).unwrap());
            eprintln!("    HIP top-5: {:?}", &indexed[..5]);

            let mut expected_indexed: Vec<_> = expected_logits.iter().enumerate().collect();
            expected_indexed.sort_by(|(_, a), (_, b)| b.partial_cmp(a).unwrap());
            eprintln!("    Expected top-5: {:?}", &expected_indexed[..5]);

            all_passed = false;
        }
    }

    assert!(
        all_passed,
        "Some steps failed ground truth comparison (need {}% within tolerance)",
        MIN_PASS_PCT
    );
    println!("\nAll {} steps passed ground truth validation!", n_steps);
}

/// Count elements within tolerance and return (pass_count, total, max_diff).
fn count_within_tolerance(
    actual: &[f32],
    expected: &[f32],
    rtol: f32,
    atol: f32,
) -> (usize, usize, f32) {
    let mut pass_count = 0;
    let mut max_diff = 0.0f32;
    for (&a, &e) in actual.iter().zip(expected.iter()) {
        let diff = (a - e).abs();
        max_diff = max_diff.max(diff);
        let threshold = atol + rtol * e.abs();
        if diff <= threshold {
            pass_count += 1;
        }
    }
    (pass_count, actual.len(), max_diff)
}

/// Get top-k indices from logits, sorted by descending logit value.
fn top_k_indices(logits: &[f32], k: usize) -> Vec<usize> {
    let mut indexed: Vec<_> = logits.iter().enumerate().collect();
    indexed.sort_by(|(_, a), (_, b)| b.partial_cmp(a).unwrap_or(std::cmp::Ordering::Equal));
    indexed.iter().take(k).map(|(i, _)| *i).collect()
}

/// Calculate overlap between two top-k sets as a fraction.
fn top_k_overlap(actual: &[usize], expected: &[usize]) -> f64 {
    let expected_set: std::collections::HashSet<_> = expected.iter().collect();
    let matches = actual.iter().filter(|i| expected_set.contains(i)).count();
    matches as f64 / expected.len() as f64
}

/// Compute ranks for a slice of values (higher value = lower rank, i.e., rank 1 is highest).
/// Handles ties by assigning average rank.
fn compute_ranks(values: &[f32]) -> Vec<f64> {
    let n = values.len();
    let mut indexed: Vec<_> = values.iter().enumerate().collect();
    // Sort by value descending (highest value gets rank 1)
    indexed.sort_by(|(_, a), (_, b)| b.partial_cmp(a).unwrap_or(std::cmp::Ordering::Equal));

    let mut ranks = vec![0.0; n];
    let mut i = 0;
    while i < n {
        // Find all elements with the same value (ties)
        let mut j = i + 1;
        while j < n && (indexed[j].1 - indexed[i].1).abs() < 1e-10 {
            j += 1;
        }
        // Assign average rank to all tied elements
        // Ranks are 1-indexed: positions i..j get average of (i+1)..(j+1)
        let avg_rank = (i + 1 + j) as f64 / 2.0;
        for k in i..j {
            ranks[indexed[k].0] = avg_rank;
        }
        i = j;
    }
    ranks
}

/// Compute Spearman's rank correlation coefficient between two slices.
/// Returns a value in [-1, 1] where 1 means perfect positive correlation.
fn spearman_correlation(a: &[f32], b: &[f32]) -> f64 {
    assert_eq!(a.len(), b.len(), "Slices must have equal length");
    let n = a.len() as f64;

    let ranks_a = compute_ranks(a);
    let ranks_b = compute_ranks(b);

    // Compute Pearson correlation of ranks
    let mean_a: f64 = ranks_a.iter().sum::<f64>() / n;
    let mean_b: f64 = ranks_b.iter().sum::<f64>() / n;

    let mut cov = 0.0;
    let mut var_a = 0.0;
    let mut var_b = 0.0;

    for i in 0..a.len() {
        let da = ranks_a[i] - mean_a;
        let db = ranks_b[i] - mean_b;
        cov += da * db;
        var_a += da * da;
        var_b += db * db;
    }

    if var_a < 1e-10 || var_b < 1e-10 {
        return 1.0; // All same values = perfect correlation
    }

    cov / (var_a.sqrt() * var_b.sqrt())
}

/// Test top-1 (argmax) match at every generation step.
///
/// This is the primary functional correctness test. Even if logit values differ
/// slightly due to BF16 vs FP32 precision, the model should produce the same
/// greedy predictions.
#[test]
#[cfg(feature = "hip")]
fn test_top1_match_all_steps() {
    if !model_exists() {
        eprintln!("Skipping test: model file not found");
        return;
    }
    if !ground_truth_fixtures_exist() {
        eprintln!("Skipping test: ground truth fixtures not found");
        return;
    }

    let config =
        TestFixture::load("tests/fixtures/ground_truth/config.npz").expect("Failed to load config");
    let tokens_i64 = config.i64("tokens");
    let n_steps = config.i64("n_steps")[0] as usize;

    use web_rwkv::hip::HipRuntimeConfig;
    let model =
        web_rwkv::hip::Rwkv7Hip::load("/workspace/models/rwkv7-g1a-0.1b-20250728-ctx4096.st")
            .expect("Failed to load model");
    let config = HipRuntimeConfig::new(256, 1);
    let model = model
        .with_config(config)
        .expect("Failed to configure model");
    let mut state: Option<web_rwkv::hip::HipState> = None;

    println!("\n=== Top-1 (Argmax) Match Test ===\n");

    let mut matches = 0;
    let mut mismatches = Vec::new();

    for step in 0..n_steps {
        let token = tokens_i64[step] as u32;
        let fixture_path = format!("tests/fixtures/ground_truth/step_{}.npz", step);
        let fixture = TestFixture::load(&fixture_path).expect("Failed to load fixture");

        let (logits, new_state) = model
            .step(&[&[token]], state)
            .expect("Step failed");
        state = Some(new_state);
        let expected_logits = fixture.f32("logits");

        let actual_top1 = top_k_indices(&logits, 1)[0];
        let expected_top1 = top_k_indices(expected_logits, 1)[0];

        if actual_top1 == expected_top1 {
            matches += 1;
            println!(
                "  Step {:2}: token {:5} -> top1={:5} ✓",
                step, token, actual_top1
            );
        } else {
            mismatches.push((step, token, actual_top1, expected_top1));
            println!(
                "  Step {:2}: token {:5} -> HIP={:5}, expected={:5} ✗",
                step, token, actual_top1, expected_top1
            );
        }
    }

    println!("\n=== Summary ===");
    println!(
        "Top-1 matches: {}/{} ({:.1}%)",
        matches,
        n_steps,
        100.0 * matches as f64 / n_steps as f64
    );

    if !mismatches.is_empty() {
        println!("\nMismatches:");
        for (step, token, actual, expected) in &mismatches {
            println!(
                "  Step {}: token {} -> HIP predicts {}, expected {}",
                step, token, actual, expected
            );
        }
    }

    assert_eq!(
        matches, n_steps,
        "All steps should have matching top-1 predictions"
    );
    println!("\n✓ All {} steps have matching top-1 predictions!", n_steps);
}

/// Test top-5 overlap at every generation step.
///
/// Validates that the top 5 candidate tokens match between HIP and reference.
/// Order may vary due to numerical precision, but the same tokens should appear.
#[test]
#[cfg(feature = "hip")]
fn test_top5_overlap_all_steps() {
    if !model_exists() || !ground_truth_fixtures_exist() {
        eprintln!("Skipping test: model or fixtures not found");
        return;
    }

    let config =
        TestFixture::load("tests/fixtures/ground_truth/config.npz").expect("Failed to load config");
    let tokens_i64 = config.i64("tokens");
    let n_steps = config.i64("n_steps")[0] as usize;

    use web_rwkv::hip::HipRuntimeConfig;
    let model =
        web_rwkv::hip::Rwkv7Hip::load("/workspace/models/rwkv7-g1a-0.1b-20250728-ctx4096.st")
            .expect("Failed to load model");
    let config = HipRuntimeConfig::new(256, 1);
    let model = model
        .with_config(config)
        .expect("Failed to configure model");
    let mut state: Option<web_rwkv::hip::HipState> = None;

    println!("\n=== Top-5 Overlap Test ===\n");

    const MIN_OVERLAP_THRESHOLD: f64 = 0.80; // 80% overlap required
    let mut total_overlap = 0.0;
    let mut steps_below_threshold = Vec::new();

    for step in 0..n_steps {
        let token = tokens_i64[step] as u32;
        let fixture_path = format!("tests/fixtures/ground_truth/step_{}.npz", step);
        let fixture = TestFixture::load(&fixture_path).expect("Failed to load fixture");

        let (logits, new_state) = model
            .step(&[&[token]], state)
            .expect("Step failed");
        state = Some(new_state);
        let expected_logits = fixture.f32("logits");

        let actual_top5 = top_k_indices(&logits, 5);
        let expected_top5 = top_k_indices(expected_logits, 5);
        let overlap = top_k_overlap(&actual_top5, &expected_top5);
        total_overlap += overlap;

        let status = if overlap >= MIN_OVERLAP_THRESHOLD {
            "✓"
        } else {
            "✗"
        };
        println!(
            "  Step {:2}: overlap={:.0}% ({}/5) {}",
            step,
            overlap * 100.0,
            (overlap * 5.0) as usize,
            status
        );

        if overlap < MIN_OVERLAP_THRESHOLD {
            steps_below_threshold.push((step, overlap, actual_top5.clone(), expected_top5.clone()));
        }
    }

    let avg_overlap = total_overlap / n_steps as f64;
    println!("\n=== Summary ===");
    println!("Average top-5 overlap: {:.1}%", avg_overlap * 100.0);
    println!(
        "Steps below {:.0}% threshold: {}",
        MIN_OVERLAP_THRESHOLD * 100.0,
        steps_below_threshold.len()
    );

    if !steps_below_threshold.is_empty() {
        println!("\nSteps with low overlap:");
        for (step, overlap, actual, expected) in &steps_below_threshold {
            println!("  Step {}: {:.0}% overlap", step, overlap * 100.0);
            println!("    HIP top-5:      {:?}", actual);
            println!("    Expected top-5: {:?}", expected);
        }
    }

    assert!(
        avg_overlap >= MIN_OVERLAP_THRESHOLD,
        "Average top-5 overlap {:.1}% below threshold {:.0}%",
        avg_overlap * 100.0,
        MIN_OVERLAP_THRESHOLD * 100.0
    );

    println!(
        "\n✓ Top-5 overlap test passed! Average: {:.1}%",
        avg_overlap * 100.0
    );
}

/// Test top-10 overlap with detailed reporting.
///
/// A more relaxed test that validates broader prediction agreement.
#[test]
#[cfg(feature = "hip")]
fn test_top10_overlap_all_steps() {
    if !model_exists() || !ground_truth_fixtures_exist() {
        eprintln!("Skipping test: model or fixtures not found");
        return;
    }

    let config =
        TestFixture::load("tests/fixtures/ground_truth/config.npz").expect("Failed to load config");
    let tokens_i64 = config.i64("tokens");
    let n_steps = config.i64("n_steps")[0] as usize;

    use web_rwkv::hip::HipRuntimeConfig;
    let model =
        web_rwkv::hip::Rwkv7Hip::load("/workspace/models/rwkv7-g1a-0.1b-20250728-ctx4096.st")
            .expect("Failed to load model");
    let config = HipRuntimeConfig::new(256, 1);
    let model = model
        .with_config(config)
        .expect("Failed to configure model");
    let mut state: Option<web_rwkv::hip::HipState> = None;

    println!("\n=== Top-10 Overlap Test ===\n");

    const MIN_OVERLAP_THRESHOLD: f64 = 0.70; // 70% overlap required for top-10
    let mut total_overlap = 0.0;

    for step in 0..n_steps {
        let token = tokens_i64[step] as u32;
        let fixture_path = format!("tests/fixtures/ground_truth/step_{}.npz", step);
        let fixture = TestFixture::load(&fixture_path).expect("Failed to load fixture");

        let (logits, new_state) = model
            .step(&[&[token]], state)
            .expect("Step failed");
        state = Some(new_state);
        let expected_logits = fixture.f32("logits");

        let actual_top10 = top_k_indices(&logits, 10);
        let expected_top10 = top_k_indices(expected_logits, 10);
        let overlap = top_k_overlap(&actual_top10, &expected_top10);
        total_overlap += overlap;

        println!(
            "  Step {:2}: overlap={:.0}% ({}/10)",
            step,
            overlap * 100.0,
            (overlap * 10.0) as usize
        );
    }

    let avg_overlap = total_overlap / n_steps as f64;
    println!("\n=== Summary ===");
    println!("Average top-10 overlap: {:.1}%", avg_overlap * 100.0);

    assert!(
        avg_overlap >= MIN_OVERLAP_THRESHOLD,
        "Average top-10 overlap {:.1}% below threshold {:.0}%",
        avg_overlap * 100.0,
        MIN_OVERLAP_THRESHOLD * 100.0
    );

    println!(
        "\n✓ Top-10 overlap test passed! Average: {:.1}%",
        avg_overlap * 100.0
    );
}

/// Test Spearman rank correlation of full logit distributions.
///
/// This is the most comprehensive functional test. It measures how well the entire
/// ranking of all 65,536 tokens correlates between HIP and reference. Unlike top-k
/// tests which only check the best predictions, this validates the full distribution.
///
/// Spearman's ρ ranges from -1 (inverse) to +1 (perfect agreement).
/// For a correct implementation, we expect ρ > 0.999.
#[test]
#[cfg(feature = "hip")]
fn test_spearman_rank_correlation() {
    if !model_exists() || !ground_truth_fixtures_exist() {
        eprintln!("Skipping test: model or fixtures not found");
        return;
    }

    let config =
        TestFixture::load("tests/fixtures/ground_truth/config.npz").expect("Failed to load config");
    let tokens_i64 = config.i64("tokens");
    let n_steps = config.i64("n_steps")[0] as usize;

    use web_rwkv::hip::HipRuntimeConfig;
    let model =
        web_rwkv::hip::Rwkv7Hip::load("/workspace/models/rwkv7-g1a-0.1b-20250728-ctx4096.st")
            .expect("Failed to load model");
    let config = HipRuntimeConfig::new(256, 1);
    let model = model
        .with_config(config)
        .expect("Failed to configure model");
    let mut state: Option<web_rwkv::hip::HipState> = None;

    println!("\n=== Spearman Rank Correlation Test ===\n");

    const MIN_CORRELATION: f64 = 0.999; // Very high threshold for functional correctness
    let mut total_rho = 0.0;
    let mut min_rho = 1.0;
    let mut min_rho_step = 0;

    for step in 0..n_steps {
        let token = tokens_i64[step] as u32;
        let fixture_path = format!("tests/fixtures/ground_truth/step_{}.npz", step);
        let fixture = TestFixture::load(&fixture_path).expect("Failed to load fixture");

        let (logits, new_state) = model
            .step(&[&[token]], state)
            .expect("Step failed");
        state = Some(new_state);
        let expected_logits = fixture.f32("logits");

        let rho = spearman_correlation(&logits, expected_logits);
        total_rho += rho;

        if rho < min_rho {
            min_rho = rho;
            min_rho_step = step;
        }

        let status = if rho >= MIN_CORRELATION { "✓" } else { "✗" };
        println!("  Step {:2}: ρ = {:.6} {}", step, rho, status);
    }

    let avg_rho = total_rho / n_steps as f64;
    println!("\n=== Summary ===");
    println!("Average Spearman ρ: {:.6}", avg_rho);
    println!("Minimum Spearman ρ: {:.6} (step {})", min_rho, min_rho_step);

    assert!(
        avg_rho >= MIN_CORRELATION,
        "Average Spearman correlation {:.6} below threshold {:.3}",
        avg_rho,
        MIN_CORRELATION
    );

    println!(
        "\n✓ Spearman rank correlation test passed! Average ρ = {:.6}",
        avg_rho
    );
}

/// Test that final logits produce expected next token prediction.
///
/// After processing the full prompt, the model should predict a reasonable
/// continuation. This is a sanity check that the model is working.
#[test]
#[cfg(feature = "hip")]
fn test_ground_truth_final_prediction() {
    if !model_exists() || !ground_truth_fixtures_exist() {
        eprintln!("Skipping test: model or fixtures not found");
        return;
    }

    // Load final step fixture
    let config =
        TestFixture::load("tests/fixtures/ground_truth/config.npz").expect("Failed to load config");
    let n_steps = config.i64("n_steps")[0] as usize;

    let final_fixture = TestFixture::load(&format!(
        "tests/fixtures/ground_truth/step_{}.npz",
        n_steps - 1
    ))
    .expect("Failed to load final step fixture");
    let expected_logits = final_fixture.f32("logits");

    // Find argmax of expected logits
    let (expected_argmax, _) = expected_logits
        .iter()
        .enumerate()
        .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
        .unwrap();

    println!(
        "Final step (after 'Assistant:') expects token {}",
        expected_argmax
    );

    // The expected next token after "Assistant:" should be reasonable
    // (e.g., a space, newline, or start of response)
    // Token 262 = " The", Token 11 = "\n", Token 209 = " "
    let reasonable_tokens = [262, 11, 209, 380, 586, 1703]; // Common response starts

    println!("Expected argmax: {}", expected_argmax);
    println!("Reasonable tokens: {:?}", reasonable_tokens);
}
